default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MatchMeWithCanada_development

test:
  <<: *default
  database: MatchMeWithCanada_test

production:
  <<: *default
  database: production_jyqu
  username: root
  password: KujEGHhpJabpsTlRi0gIgP1YFYX5BtJB
